Tasks/hh 1 header
LightC0de/honey-holic pull request #2
Opened 2019-05-26 12:46 UTC by IgorTeplov

Адаптивное меню. Desktop сделал по макету. Для всего остального(hover and active effects, вид на моб. устройствах) нужен макет.

2019-05-26 14:32 UTC, kengup commented on sass/modules/header.sass
>      line-height: 18px
указание высоты строки в рх

2019-05-26 14:33 UTC, kengup commented on sass/modules/header.sass
>      font-size: 16px
указание размера шрифта в рх

2019-05-26 14:33 UTC, kengup commented on sass/modules/header.sass
>      line-height: 18px
указание высоты строки в рх

2019-05-26 14:33 UTC, kengup commented on sass/modules/header.sass
>      font-size: 16px
указание размера шрифта в рх

2019-05-26 14:33 UTC, kengup commented on sass/modules/header.sass
>      line-height: 16px
рх

2019-05-26 14:33 UTC, kengup commented on sass/modules/header.sass
>      font-size: 16px
рх

2019-05-27 04:26 UTC, LightC0de requested changes
См. комменты

2019-05-27 04:26 UTC, LightC0de commented on sass/components/primary-button.sass
> +    border: 0px solid black
Попробуй border: none

2019-05-27 04:26 UTC, LightC0de commented on sass/modules/header.sass
> +@import '../colors'
Добавь после импорта отступ в 1 строку

2019-05-27 04:26 UTC, LightC0de commented on sass/modules/header.sass
> +        margin: 0px 14px 0px 0px
margin-right

2019-05-27 04:26 UTC, LightC0de commented on sass/modules/header.sass
> +.btn-language
Договорились же переопределять стандартные классы кнопок (btn-primary, btn-secondary, btn-outline...)

2019-05-27 04:26 UTC, LightC0de commented on sass/modules/header.sass
> +@media (max-width: 767px)
@media пишутся в самом внизу с сохранением структуры

2019-05-27 04:26 UTC, LightC0de commented on sass/modules/header.sass
> +    margin: 20px 32px
Посмотри, возможно есть смысл использовать rem (см. footer.sass > .card)

2019-06-10 08:20 UTC, IgorTeplov commented on sass/components/primary-button.sass
> +    border: 0px solid black
есть

2019-06-10 08:20 UTC, IgorTeplov commented on sass/modules/header.sass
> +@import '../colors'
подключил в main

2019-06-10 08:20 UTC, IgorTeplov commented on sass/modules/header.sass
> +        margin: 0px 14px 0px 0px
есть

2019-06-10 08:20 UTC, IgorTeplov commented on sass/modules/header.sass
> +.btn-language
готово

2019-06-10 08:20 UTC, IgorTeplov commented on sass/modules/header.sass
> +@media (max-width: 767px)
сделано

2019-06-10 08:23 UTC, IgorTeplov commented on sass/modules/header.sass
> +    margin: 20px 32px
готово

2019-06-12 08:43 UTC, closed without merging