added adaptive slider to main stock block
LightC0de/honey-holic pull request #3
Opened 2019-05-26 14:30 UTC by kengup

2019-05-27 04:02 UTC, LightC0de requested changes
См. комменты

2019-05-27 04:02 UTC, ask-danylo commented on sass/modules/mainpage.sass
> +    .slick-list::after
https://css-tricks.com/the-sass-ampersand/#article-header-id-3

2019-05-27 04:02 UTC, ask-danylo commented on sass/modules/mainpage.sass
> +    .slick-list::before
https://css-tricks.com/the-sass-ampersand/#article-header-id-3

2019-05-27 04:02 UTC, ask-danylo commented on sass/modules/mainpage.sass
> +    .stock-slider-block
&-block

2019-05-27 04:02 UTC, ask-danylo commented on index.html
> +                    <br><br> Мі це змінили!
Лучше разбить каждый абзац в p и задать расстояние между ними вместо br

2019-05-27 04:02 UTC, ask-danylo commented on index.html
> +                    <br><br> Мі це змінили!
![image](https://user-images.githubusercontent.com/42488785/58393954-b211f500-8049-11e9-9b18-67bd8a556d98.png)
Как вариант сделать мягкий переход тоже (как справа)

2019-05-27 04:02 UTC, ask-danylo commented on index.html
> +                            <div>Весільні подарунки</div>
Почему div? Есть же span, p

2019-05-27 04:02 UTC, ask-danylo commented on sass/modules/mainpage.sass
> +.right
Некорректное название класса (нужно ограничить область применения):
обернуть весь блок в section с уникальным классом (например mainpage-slider)

(см. пример footer.sass - все стили ограничены селектором footer)

2019-05-27 04:02 UTC, ask-danylo commented on sass/modules/mainpage.sass
> +        padding: 20px
Попробуй сделать через rem, тогда на моб. версии не будет такого жирного отступа (см. пример footer .card - padding)

2019-05-27 04:02 UTC, LightC0de commented on sass/modules/mainpage.sass
> +        padding: 0 15px !important
Желательно избегать important. Попробуй с помощью приоритетов стилей перебить стили (например

section.mainpage-slider .right { padding: 0 15px }

2019-05-27 22:00 UTC, kengup commented on sass/modules/mainpage.sass
> +    .slick-list::after
+

2019-05-27 22:00 UTC, kengup commented on sass/modules/mainpage.sass
> +    .slick-list::before
+

2019-05-27 22:00 UTC, kengup commented on sass/modules/mainpage.sass
> +    .stock-slider-block
+

2019-05-27 22:00 UTC, kengup commented on index.html
> +                    <br><br> Мі це змінили!
+

2019-05-27 22:02 UTC, kengup commented on index.html
> +                            <div>Весільні подарунки</div>
div занимает всю ширину блока по умолчанию, что позволяет легко ориентировать текст по центру

2019-05-27 22:05 UTC, kengup commented on sass/modules/mainpage.sass
> +.right
+

2019-05-27 22:06 UTC, kengup commented on sass/modules/mainpage.sass
> +        padding: 20px
+

2019-05-27 22:07 UTC, kengup commented on sass/modules/mainpage.sass
> +        padding: 0 15px !important
+

2019-05-28 02:57 UTC, LightC0de commented on sass/modules/mainpage.sass
> +    .slick-list::after
Ток отступы убери и ок (27, 37)
![image](https://user-images.githubusercontent.com/42488785/58447587-86584300-810d-11e9-85b4-d1c98d97a3e0.png)

2019-05-28 03:00 UTC, LightC0de commented on sass/modules/mainpage.sass
> +        padding: 0 15px !important
Содержательный ответ

2019-05-28 03:01 UTC, LightC0de commented on index.html
> +                    <br><br> Мі це змінили!
Красавчик!

2019-05-28 03:01 UTC, LightC0de commented on index.html
> +                    <br><br> Мі це змінили!
Ток убери все же br

2019-05-28 03:03 UTC, LightC0de commented on index.html
> +                            <div>Весільні подарунки</div>
![image](https://user-images.githubusercontent.com/42488785/58447816-5f4e4100-810e-11e9-981f-33c7e0726591.png)

2019-05-28 12:39 UTC, kengup commented on sass/modules/mainpage.sass
> +    .slick-list::after
эти два селектора относятся к slick-list, далее идут селекторы с амперсандом, которые относятся к stock-slider

2019-05-28 12:41 UTC, kengup commented on sass/modules/mainpage.sass
> +    .slick-list::after
убрал

2019-05-28 12:44 UTC, kengup commented on index.html
> +                            <div>Весільні подарунки</div>
есть

2019-05-28 12:44 UTC, kengup commented on sass/modules/mainpage.sass
> +        padding: 0 15px !important
это гитхаб не умеет в знак плюса

2019-05-28 12:47 UTC, kengup commented on index.html
> +                    <br><br> Мі це змінили!
убрал

2019-06-10 18:53 UTC, closed without merging