tasks/HH-11 and 13
LightC0de/honey-holic pull request #8
Opened 2019-06-10 08:10 UTC by IgorTeplov

2019-06-15 17:13 UTC, LightC0de requested changes
Выпили шрифты

2019-06-16 12:41 UTC, kengup commented
ok

2019-06-17 10:53 UTC, ask-danylo commented on product.html
> +    <script src="js/color.js"></script>
Выпилить color.js (так же и сам файл)

2019-06-17 10:53 UTC, ask-danylo commented on sass/components/arrow.sass
> +.up
Непонятное название компонента и класса

2019-06-17 11:36 UTC, LightC0de approved these changes

2019-06-17 12:26 UTC, kengupich reviewed
1

2019-06-17 12:26 UTC, kengup commented on sass/modules/product.sass
> +        $rdius: 12px
здесь нет опечатки?
было бы здорово вынести переменную вверх

2019-06-17 12:26 UTC, kengup commented on sass/modules/product.sass
> +            height: 12px
принудительная установка высоты в блоке с текстом может привести к некорректной работе с изменением разрешения экрана и кегля

2019-06-17 12:26 UTC, kengup commented on sass/modules/product.sass
> +            width: 44px
было бы правильнее установить здесь auto

2019-06-17 12:26 UTC, kengup commented on sass/modules/product.sass
> +        margin: 23px 0px
лучше заменить на 2rem

2019-06-17 12:47 UTC, merged