header
LightC0de/honey-holic pull request #9
Opened 2019-06-10 19:12 UTC by IgorTeplov

2019-06-15 17:11 UTC, LightC0de requested changes
1. ограничь стили в header.sass
2. за что отвечает .btn-success? В одном файле компонента - один компонент (у тебя сейчас их там два)
3. Цвета в компонентах через переменные или функции lighten() darken()

2019-06-15 17:11 UTC, ask-danylo commented on sass/components/primary-button.sass
> +    &:focus, &:hover, &:active, &:visited, &:active:focus, &:active:hover
Зачем это?
Если что обводку я глобально поправил

2019-06-15 17:11 UTC, ask-danylo commented on sass/components/primary-button.sass
> +        box-shadow: 0 7px 7px 0 rgba(147,211,67,0.18)
Цвет через наши переменные (colors.sass)
Погугли - sass lighten() darken()

Не обязательно прям на 100% соответствие цветов - на глаз макс. похожий вариант.
Еще в sass есть функция, чтобы понизить прозрачность цвета - погугли

2019-06-16 13:17 UTC, LightC0de approved these changes

2019-06-16 14:07 UTC, kengup commented
ok

2019-06-16 18:43 UTC, merged